# Generated by Django 3.1.4 on 2021-03-09 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('start_price', models.IntegerField(null=True)),
                ('end_price', models.IntegerField(blank=True, null=True)),
                ('auction_length', models.DateTimeField(null=True)),
                ('auction_start', models.DateTimeField(auto_now=True, null=True)),
                ('auction_end', models.DateTimeField(auto_now=True, null=True)),
                ('auction_winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('comment_date', models.DateTimeField(auto_now=True, null=True)),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_bid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('current_bid', models.IntegerField(blank=True, null=True)),
                ('winning_bid', models.BooleanField(blank=True, null=True)),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listings')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='my_bids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
    ]
