# Generated by Django 3.1.4 on 2021-03-09 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210308_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listing_bid',
            new_name='bid_amount',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='comments',
            name='current_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='listing_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='winning_bid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='my_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.comments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_bids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
    ]
