# Generated by Django 3.1.4 on 2021-03-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210308_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.URLField(max_length=350, null=True),
        ),
    ]
