# Generated by Django 3.1.4 on 2021-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210311_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
