# Generated by Django 3.1.4 on 2021-03-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='auction_winner',
            new_name='owner',
        ),
    ]
