# Generated by Django 3.1.4 on 2021-03-16 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210315_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='auction_length',
        ),
        migrations.AlterField(
            model_name='listing',
            name='auction_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 23, 13, 5, 40, 916473), null=True),
        ),
    ]
